#!/usr/bin/env bash
set -e
if [[ "$1" == "-d" ]]; then
  shift
  if [[ -z "$1" || "$1" == "-" ]]; then
    /usr/bin/base64 -D
  else
    /usr/bin/base64 -D -i "$1"
  fi
else
  /usr/bin/base64 "$@"
fi
